### ISSUE TITLE
Expose methods that render to Stream[F, String]

### ISSUE THREAD

**Issue by matthughes** [sovt/spata#28]
Rendering a CSV for consumption via http4s requires a `Stream[F, Byte]`.  However, the current API only exposes a render method that builds `Stream[F, Char].`  The only safe way to convert that to Byte is to do something like:

```scala
.render
.through(fs2.text.char2string)
.through(fs2.text.utf8.encode)
```

Can we refactor this to expose a `renderString` method.  We already have a Stream[String] up to the last line but then convert to chars.

```scala
  def render: Pipe[F, Record, Char] = (in: Stream[F, Record]) =>
    def loop(in: Stream[F, Record], header: Header): Pull[F, Either[HeaderError, String], Unit] =
      in.pull.uncons.flatMap:
        case Some((rc, t)) => Pull.output(rc.map(renderRow(_, header))) >> loop(t, header)
        case None => Pull.done
    val pull = in.pull.uncons1.flatMap:
      case Some((r, t)) =>
        val headerRow = if config.hasHeader then Pull.output1(renderHeader(r.header)) else Pull.pure(())
        val firstRow = Pull.output1(renderRow(r, r.header))
        headerRow >> firstRow >> loop(t, r.header)
      case None => Pull.done
    pull.stream.through(toChars)

  private def toChars: Pipe[F, EHE[String], Char] = (in: Stream[F, EHE[String]]) =>
    in.rethrow
      .intersperse(srd)
      .map(s => Chunk.array[Char](s.toCharArray))
      .flatMap(Stream.chunk)
```

**Comment by susuro** [comment]
I agree that the current API requires unnecessary conversion. Would you like to make a PR for this? I think this should be implemented for both `parse` methods.
To keep the API of rendering and parsing in some symmetry, we should probably introduce `parseString` in the parser. However, it won't have any performance benefit, and there are other methods in `CSVRenderer` which require a stream of characters, so I'm not sure about this. What do you think?
