### ISSUE TITLE
Feature request: Allow the Decoded type to be validated 

### ISSUE THREAD

**Issue by calvinlfer** [sovt/spata#34]
I have a use case at work where I parse CSV into my data type. I make use of the Record API to extract certain fields that need to go through additional runtime validations before calling record.to[MyCaseClass]. 

Is it possible to expose some failure constructors (like Decoded.fail(message, record)) that would allow the line number and other relevant info to be preserved in the exception or should I be utilizing a different API in order to do this? Thank you very much

**Comment by calvinlfer** [comment]
Update: I think I can implement my own StringParser for that particular type and that could perform this additional validations as part of parsing the string into the type 💡

**Comment by calvinlfer** [comment]
Confirmed, this was a better way to go about it. I had to create givens for StringParser[MyType] where I had access to perform those runtime validations and that took care of it.

**Comment by susuro** [comment]
I am glad that you found a solution that worked for you.

You may also look at [schema validation](https://github.com/fingo/spata?tab=readme-ov-file#schema-validation), which should address your requirement nicely. It allows additional validation to be defined and yields a stream of `cats.Validated`, preserving the complete error diagnostic data for each record. The API: [CSVSchema](https://javadoc.io/doc/info.fingo/spata_3/latest/index.html).
An example of how to use the validation may be found here: [ValidateITS.scala](https://github.com/fingo/spata/blob/master/src/test/scala/info/fingo/sample/spata/ValidateITS.scala).
